### ISSUE TITLE
FYI - Dependencies for Debian Buster

### ISSUE THREAD

**Issue by Person-93** [chaaz/versio#10]
**Describe the bug**
Does not compile on Debian Buster even if gpg is installed.

**To Reproduce**
`cargo install --locked versio`

**Expected behavior**
Successful installation.

**Fix**
`sudo apt install libgpg-error-dev libgpgme-dev`

**Comment by chaaz** [comment]
Ah, that's good to know; that's a precondition of the gpg libs that Versio uses. I'll add those steps (and the MacOS and Windows equivalent) to the installation instructions, since I don't think there's any way to avoid needing those.

They should only need to be installed for the `cargo install` method, though. Downloading the binaries directly shouldn't require the dev packages to be installed.
