### ISSUE TITLE
please add hotfix support

### ISSUE THREAD

**Issue by kisdaniel** [chaaz/versio#11]
versio tool is excellent if you use trunk base development git strategy, but if you want to use gitflow or oneflow you may need to make a hotfix releases.

If your main branch is going ahead after making a release 1.0.0 and you put it to production environment, and than you have to make a new release to uat environment 2.0.0 with new features, and then you get a bug from production environment you have to make a hotfix release from 1.0.0 with name 1.0.1.

How can I make a release based on 1.0.0 version if 2.0.0 already exists?
At that time versio-prev tag contains 2.0.0 version number.

**Comment by chaaz** [comment]
That's a good point, @kisdaniel ! I use gitflow myself for some projects, so I'll think about how Versio can best be used in those situations. :thinking:

**Comment by chaaz** [comment]
@kisdaniel , I believe that the correct use here would be to make use of the "prev tag" option. What you want to do for a hotfix is have the hotfix branch use a different tag instead of `versio-prev`. I've briefly tested this, and it seems to work ok:

1. Create a new branch as normal for a hotfix: this will be at a branch-point, where the branch diverges from the main release trunk. E.g. `git checkout -b hotfix-1234 v1.0.0`
2. Tag the branch-point with a unique "prev" tag; something based on the branch name would be ideal. E.g. `git tag versio-prev-hotfix-1234`. If there are specific project versions you want that branch to start from, you can help the process by annotating the tag: `git tag -f -a -m '{"versions":{"1":"0.1.2","2":"5.2.1"}}' versio-prev-hotfix-1234`. Otherwise, Versio will try to figure it out.
3. Change the `prev-tag` option in the `.versio.yaml` file in that new branch to point to your new "prev tag":
```
options:
  prev_tag: "versio-prev-hotfix-1234"
```
4. Commit / push your change. `git commit -am 'build: update versio for branch' ; git push -u origin hotfix-1234`
5. Now the hotfix branch will use `versio-prev-hotfix-1234` instead of `versio-prev` as its "prev tag". But because you didn't change the `.versio.yaml` file on the main branch, main will still use `versio-prev`.
7. You can `versio release` as normal on both the main branch and the hotfix branch independently. The first time you run it on the hotfix branch, it will re-calculate the version number based on your annotation, and/or whatever tags exist on or before the branch-point.

**Warning**, however: Versio will not guard against re-using version numbers: it's possible that you could inadvertently release e.g. v1.0.1 on both the main branch and the hotfix branch: in that case, the tag will move to whichever is released last, which is probably not what you want. Be certain that you aren't clobbering your version numbers when you release. `versio release --dry-run` might be useful here.

This is a manual chore, to be sure: I'll think about adding something to Versio to help automate this, and certainly will document it in this in the use cases. Let me know if this seems like it will work for you, and/or what might help you here.

**Comment by chaaz** [comment]
I've included the above instructions in Gitflow / Oneflow use case documentation. I've used them multiple times now on many different branches and branch types, and it seems to work well if you're careful. In the future, we may include some tooling to make this use case more automated, but for now I'm considering the issue settled. Thanks for your input!
